version: 0.2

env:
  variables:
    NAME: "test"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies"
      - npm install
      - npm install -g snyk
      - echo "Install complete"
  pre_build:
    commands:
      - snyk config set token=$SNYK_TOKEN
      - echo "Snyk authentication configured"
  build:
    commands:
      - echo "Starting Snyk code scan"
      - snyk code test --severity-threshold=high
      - echo "Build completed $NAME"
  post_build:
    commands:
      - snyk monitor
      - echo "Snyk monitoring initialized"
      - echo "Post-build completed"
      - npm uninstall -g snyk
