version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies"
      - npm install
      - npm install -g snyk
      - echo "Install complete"
  pre_build:
    commands:
      - snyk config set token=$SNYK_TOKEN
      - echo "Snyk authentication configured"
  build:
    commands:
      - echo "Starting Snyk open source test"
      - snyk test
      - echo "Starting Snyk code scan"
      - snyk code test --severity-threshold=high
      - echo "Scanning with --dev dependencies"
      - snyk test --dev
      - echo "Build completed"
  post_build:
    commands:
      - snyk monitor
      - echo "Snyk monitoring initialized"
      - echo "Post-build completed"
